'use_strict';

import { observable, configure } from 'mobx';

import x from 'x';
import * as img_loading from 'options/img_loading';
import * as settings from 'options/settings';

configure({ enforceActions: 'observed' });

//--

export const inputs_data = observable({
    obj: {
        upload: {
            paste: {
                key: x.unique_id(),
                family: 'upload',
                name: 'paste',
                type: 'input',
                val: '',
                visible: true,
                add_help: true,
                on_paste: img_loading.get_pasted_image_or_image_url,
                entered_one_char_in_text_input_after_focus: false,
            },
            download_img_when_link_given: {
                key: x.unique_id(),
                family: 'upload',
                name: 'download_img_when_link_given',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
            },
            create_solid_color_img: {
                key: x.unique_id(),
                family: 'upload',
                name: 'create_solid_color_img',
                type: 'color',
                val: '',
                global_checkbox_val: false,
                visible: true,
                vizualization_color: '#ffffff',
                color_pickier_is_visible: false,
                color_pickier_position: 'top',
                changed_color_once_after_focus: false,
            },
        },
        img_settings: {
            mode: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'mode',
                type: 'select',
                val: '',
                visible: true,
                add_help: true,
            },
            change_interval: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'change_interval',
                type: 'select',
                val: '',
            },
            keep_old_themes_imgs: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'keep_old_themes_imgs',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
            },
            slideshow: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'slideshow',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
            },
            img_change_effect: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'img_change_effect',
                type: 'select',
                val: '',
            },
            slide_direction: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'slide_direction',
                type: 'select',
                val: '',
            },
            shuffle: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'shuffle',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
            },
            current_img: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'current_img',
                type: 'input',
                val: '',
                visible: false,
                adjacent_btn_is_visible: true,
                add_help: false,
                on_input: settings.change_current_img_by_typing_into_currrent_img_input,
                on_blur: settings.correct_current_img_input_val,
                entered_one_char_in_text_input_after_focus: false,
            },
            set_last_uploaded: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'set_last_uploaded',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
            },
            separator: {
                key: x.unique_id(),
                type: 'separator',
            },
            settings_type: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'settings_type',
                type: 'select',
                val: 'global',
                visible: true,
                add_help: true,
            },
            size: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'size',
                type: 'select',
                val: '',
                visible: true,
                add_help: true,
            },
            position: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'position',
                type: 'select',
                val: '',
                visible: true,
            },
            repeat: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'repeat',
                type: 'select',
                val: '',
                visible: true,
            },
            color: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'color',
                type: 'color',
                val: '',
                global_checkbox_val: false,
                visible: true,
                include_global_checkbox: true,
                vizualization_color: '#ffffff',
                color_pickier_is_visible: false,
                color_pickier_position: 'top',
                changed_color_once_after_focus: false,
            },
            video_volume: {
                key: x.unique_id(),
                family: 'img_settings',
                name: 'video_volume',
                type: 'slider',
                val: 0,
                global_checkbox_val: false,
                visible: true,
                include_global_checkbox: true,
                adjusting_slider_once_after_focus: false,
            },
        },
        other_settings: {
            enable_analytics: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'enable_analytics',
                type: 'checkbox',
                checkbox_type: 'permissions',
                permissions: [{ origins: ['https://www.google-analytics.com/*'] }],
                val: false,
                visible: true,
            },
            show_link_to_default_new_tab: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'show_link_to_default_new_tab',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
                visible: true,
            },
            show_bookmarks_bar: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'show_bookmarks_bar',
                type: 'checkbox',
                checkbox_type: 'permissions',
                permissions: [{ permissions: ['bookmarks'] }],
                val: false,
                visible: true,
            },
            enable_paste: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'enable_paste',
                type: 'checkbox',
                checkbox_type: 'permissions',
                permissions: [{ permissions: ['clipboardRead'] }],
                val: false,
                visible: true,
            },
            allow_downloading_images_by_link: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'allow_downloading_images_by_link',
                type: 'checkbox',
                checkbox_type: 'permissions',
                permissions: [{ origins: ['*://*/*'] }],
                val: false,
                visible: true,
            },
        },
    },
});
