import { observable, configure } from 'mobx';

import x from 'x';
import * as background_loading from 'options/background_loading';
import * as settings from 'options/settings';
import * as background_deletion from 'options/background_deletion';

configure({ enforceActions: 'observed' });

export const inputs_data = observable({
    obj: {
        upload: {
            paste: {
                key: x.unique_id(),
                family: 'upload',
                name: 'paste',
                type: 'input',
                val: '',
                visible: true,
                add_help: true,
                on_paste: background_loading.get_pasted_image_or_image_url,
                entered_one_char_in_text_input_after_focus: false,
            },
            download_img_when_link_given: {
                key: x.unique_id(),
                family: 'upload',
                name: 'download_img_when_link_given',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
            },
            create_solid_color_img: {
                key: x.unique_id(),
                family: 'upload',
                name: 'create_solid_color_img',
                type: 'color',
                val: '',
                global_checkbox_val: false,
                visible: true,
                vizualization_color: '#ffffff',
                color_pickier_is_visible: false,
                color_pickier_position: 'top',
                changed_color_once_after_focus: false,
            },
            load_theme_background: {
                key: x.unique_id(),
                family: 'upload',
                name: 'load_theme_background',
                type: 'btn',
                on_click: background_loading.load_theme_background_when_clicking_on_load_theme_background_btn,
            },
        },
        background_settings: {
            mode: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'mode',
                type: 'select',
                val: '',
                visible: true,
                add_help: true,
            },
            change_interval: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'change_interval',
                type: 'select',
                val: '',
            },
            keep_old_themes_backgrounds: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'keep_old_themes_backgrounds',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
            },
            slideshow: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'slideshow',
                premium: false,
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
            },
            background_change_effect: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'background_change_effect',
                type: 'select',
                val: '',
            },
            slide_direction: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'slide_direction',
                type: 'select',
                val: '',
            },
            shuffle: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'shuffle',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
            },
            current_background: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'current_background',
                type: 'input',
                val: '',
                visible: false,
                adjacent_btn_is_visible: true,
                add_help: false,
                on_input: settings.change_current_background_by_typing_into_currrent_background_input,
                on_blur: settings.correct_current_background_input_val,
                entered_one_char_in_text_input_after_focus: false,
            },
            set_last_uploaded: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'set_last_uploaded',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
            },
            separator: {
                key: x.unique_id(),
                type: 'separator',
            },
            settings_type: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'settings_type',
                type: 'select',
                val: 'global',
                visible: true,
                add_help: true,
            },
            size: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'size',
                type: 'select',
                val: '',
                visible: true,
                add_help: true,
            },
            position: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'position',
                type: 'select',
                val: '',
                visible: true,
            },
            repeat: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'repeat',
                type: 'select',
                val: '',
                visible: true,
            },
            color: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'color',
                type: 'color',
                val: '',
                global_checkbox_val: false,
                visible: true,
                include_global_checkbox: true,
                vizualization_color: '#ffffff',
                color_pickier_is_visible: false,
                color_pickier_position: 'top',
                changed_color_once_after_focus: false,
            },
            video_volume: {
                key: x.unique_id(),
                family: 'background_settings',
                name: 'video_volume',
                type: 'slider',
                val: 0,
                global_checkbox_val: false,
                visible: true,
                include_global_checkbox: true,
                adjusting_slider_once_after_focus: false,
            },
        },
        other_settings: {
            restore_defaults: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'restore_defaults',
                type: 'btn',
                on_click: settings.restore_defaults,
                visible: true,
            },
            delete_all_backgrounds: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'delete_all_backgrounds',
                type: 'btn',
                on_click: background_deletion.delete_all_images,
                visible: true,
            },
            allow_analytics: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'allow_analytics',
                type: 'checkbox',
                checkbox_type: 'permissions',
                permissions: xcon.analytics_permissions, // if you change this permissions also change it in background onmessage (check_if_analytics_enabled)
                val: false,
                visible: true,
            },
            show_link_to_default_new_tab: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'show_link_to_default_new_tab',
                type: 'checkbox',
                checkbox_type: 'ed',
                val: false,
                visible: env.what_browser === 'chrome',
            },
            show_bookmarks_bar: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'show_bookmarks_bar',
                premium: false,
                type: 'checkbox',
                checkbox_type: 'permissions',
                permissions: [{ permissions: ['bookmarks'] }],
                val: false,
                visible: false,
            },
            enable_paste: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'enable_paste',
                premium: false,
                type: 'checkbox',
                checkbox_type: 'permissions',
                permissions: [{ permissions: ['clipboardRead'] }],
                val: false,
                visible: true,
            },
            allow_downloading_imgs_by_link: {
                key: x.unique_id(),
                family: 'other_settings',
                name: 'allow_downloading_imgs_by_link',
                type: 'checkbox',
                checkbox_type: 'permissions',
                permissions: [{ origins: ['*://*/*'] }],
                val: false,
                visible: true,
            },
        },
    },
});
